################
# GitLabCI template for Drupal projects.
################

include:
  - project: $_GITLAB_TEMPLATES_REPO
    ref: $_GITLAB_TEMPLATES_REF
    file:
      - '/includes/include.drupalci.main.yml'
      - '/includes/include.drupalci.variables.yml'
      - '/includes/include.drupalci.workflows.yml'
#
################
# Pipeline configuration variables are defined with default values and descriptions in the file
# https://git.drupalcode.org/project/gitlab_templates/-/blob/main/includes/include.drupalci.variables.yml
################
variables:
  SKIP_CSPELL: "1"
  OPT_IN_TEST_MAX_PHP: 0
  OPT_IN_TEST_PREVIOUS_MAJOR: 1
  OPT_IN_TEST_NEXT_MAJOR: 0
  OPT_IN_TEST_CURRENT: 0

################
# Variable overrides for domain testing.
################
.test-variables:
  variables:
    SIMPLETEST_BASE_URL: "http://localhost/$_WEB_ROOT"
.phpunit-base:
  before_script:
    - echo "127.0.0.1 localhost" >> /etc/hosts
    - echo "127.0.0.1 group-0.localhost" >> /etc/hosts
    - echo "127.0.0.1 group-1.localhost" >> /etc/hosts
    - echo "127.0.0.1 group-2.localhost" >> /etc/hosts
    - echo "127.0.0.1 group-3.localhost" >> /etc/hosts
    - echo "127.0.0.1 group-4.localhost" >> /etc/hosts
    - echo "127.0.0.1 group-5.localhost" >> /etc/hosts
    - echo "127.0.0.1 group-6.localhost" >> /etc/hosts

phpunit:
  parallel:
    matrix:
      # Run test groups in parallel. This also speeds up identification of failing tests.
      - _PHPUNIT_EXTRA: [ "--group localgov_microsites_group", "--group localgov_microsites_blogs", "--group localgov_microsites_directories", "--group localgov_microsites_events", "--group localgov_microsites_group_term_ui", "--group localgov_microsites_group_webform", "--group localgov_microsites_news" ]
