<?php

/**
 * @file
 * LocalGov Microsites Directories module file.
 */

use Drupal\localgov_microsites_group\RolesHelper;

/**
 * Implements hook_localgov_microsites_roles_default().
 */
function localgov_microsites_news_localgov_microsites_roles_default() {
  return [
    'global' => [
      RolesHelper::MICROSITES_CONTROLLER_ROLE => [
        'view directory facets',
      ],
      RolesHelper::MICROSITES_EDITOR_ROLE => [
        'view directory facets',
      ],
    ],
    'group' => [
      RolesHelper::GROUP_ADMIN_ROLE => [
        'create group_node:localgov_news_article entity',
        'create group_node:localgov_newsroom entity',
        'delete any group_node:localgov_news_article content',
        'delete any group_node:localgov_news_article entity',
        'delete any group_node:localgov_newsroom content',
        'delete any group_node:localgov_newsroom entity',
        'delete own group_node:localgov_news_article content',
        'delete own group_node:localgov_news_article entity',
        'delete own group_node:localgov_newsroom content',
        'delete own group_node:localgov_newsroom entity',
        'update any group_node:localgov_news_article content',
        'update any group_node:localgov_news_article entity',
        'update any group_node:localgov_newsroom content',
        'update any group_node:localgov_newsroom entity',
        'update own group_node:localgov_news_article content',
        'update own group_node:localgov_news_article entity',
        'update own group_node:localgov_newsroom content',
        'update own group_node:localgov_newsroom entity',
        'view group_node:localgov_news_article content',
        'view group_node:localgov_news_article entity',
        'view group_node:localgov_newsroom content',
        'view group_node:localgov_newsroom entity',
        'view unpublished group_node:localgov_news_article entity',
        'view unpublished group_node:localgov_newsroom entity',
      ],
      RolesHelper::GROUP_ANONYMOUS_ROLE => [
        'view group_node:localgov_news_article entity',
        'view group_node:localgov_newsroom entity',
      ],
      RolesHelper::GROUP_MEMBER_ROLE => [
        'create group_node:localgov_news_article entity',
        'create group_node:localgov_newsroom entity',
        'update any group_node:localgov_news_article content',
        'update any group_node:localgov_news_article entity',
        'update any group_node:localgov_newsroom content',
        'update any group_node:localgov_newsroom entity',
        'update own group_node:localgov_news_article content',
        'update own group_node:localgov_news_article entity',
        'update own group_node:localgov_newsroom content',
        'update own group_node:localgov_newsroom entity',
        'view group_node:localgov_news_article entity',
        'view group_node:localgov_newsroom entity',
        'view unpublished group_node:localgov_news_article entity',
        'view unpublished group_node:localgov_newsroom entity',
      ],
      RolesHelper::GROUP_OUTSIDER_ROLE => [
        'view group_node:localgov_news_article entity',
        'view group_node:localgov_newsroom entity',
      ],
    ],
  ];
}
