<?php

/**
 * @file
 * LocalGov Microsites Events module file.
 */

use Drupal\localgov_microsites_group\RolesHelper;

/**
 * Implements hook_localgov_microsites_roles_default().
 */
function localgov_microsites_events_localgov_microsites_roles_default() {
  return [
    'global' => [
      RolesHelper::MICROSITES_CONTROLLER_ROLE => [
        'access localgov_geo_library entity browser pages',
        'create geo',
        'delete geo',
        'edit geo',
      ],
      RolesHelper::MICROSITES_EDITOR_ROLE => [
        'access localgov_geo_library entity browser pages',
        'create geo',
        'delete geo',
        'edit geo',
      ],
    ],
    'group' => [
      RolesHelper::GROUP_ADMIN_ROLE => [
        'access group_term overview',
        'create group_node:localgov_event entity',
        'create group_term:localgov_event_category entity',
        'create group_term:localgov_event_locality entity',
        'create group_term:localgov_event_price entity',
        'delete any group_node:localgov_event content',
        'delete any group_node:localgov_event entity',
        'delete own group_node:localgov_event content',
        'delete own group_node:localgov_event entity',
        'delete any group_term:localgov_event_category content',
        'delete any group_term:localgov_event_category entity',
        'delete any group_term:localgov_event_locality content',
        'delete any group_term:localgov_event_locality entity',
        'delete any group_term:localgov_event_price content',
        'delete any group_term:localgov_event_price entity',
        'delete own group_term:localgov_event_category content',
        'delete own group_term:localgov_event_locality content',
        'delete own group_term:localgov_event_price content',
        'update any group_node:localgov_event content',
        'update any group_node:localgov_event entity',
        'update own group_node:localgov_event content',
        'update own group_node:localgov_event entity',
        'update any group_term:localgov_event_category content',
        'update any group_term:localgov_event_category entity',
        'update any group_term:localgov_event_locality content',
        'update any group_term:localgov_event_locality entity',
        'update any group_term:localgov_event_price content',
        'update any group_term:localgov_event_price entity',
        'update own group_term:localgov_event_category content',
        'update own group_term:localgov_event_locality content',
        'update own group_term:localgov_event_price content',
        'view any unpublished group_term:localgov_event_category entity',
        'view any unpublished group_term:localgov_event_locality entity',
        'view any unpublished group_term:localgov_event_price entity',
        'view group_node:localgov_event content',
        'view group_node:localgov_event entity',
        'view group_term:localgov_event_category content',
        'view group_term:localgov_event_category entity',
        'view group_term:localgov_event_locality content',
        'view group_term:localgov_event_locality entity',
        'view group_term:localgov_event_price content',
        'view group_term:localgov_event_price entity',
        'view unpublished group_node:localgov_event entity',
      ],
      RolesHelper::GROUP_ANONYMOUS_ROLE => [
        'view group_node:localgov_event entity',
      ],
      RolesHelper::GROUP_MEMBER_ROLE => [
        'access group_term overview',
        'create group_node:localgov_event entity',
        'create group_term:localgov_event_category entity',
        'create group_term:localgov_event_locality entity',
        'create group_term:localgov_event_price entity',
        'delete any group_term:localgov_event_category entity',
        'delete any group_term:localgov_event_locality entity',
        'delete any group_term:localgov_event_price entity',
        'update any group_node:localgov_event content',
        'update any group_node:localgov_event entity',
        'update own group_node:localgov_event content',
        'update own group_node:localgov_event entity',
        'update any group_term:localgov_event_category entity',
        'update any group_term:localgov_event_locality entity',
        'update any group_term:localgov_event_price entity',
        'view any unpublished group_term:localgov_event_category entity',
        'view any unpublished group_term:localgov_event_locality entity',
        'view any unpublished group_term:localgov_event_price entity',
        'view group_node:localgov_event entity',
        'view group_term:localgov_event_category entity',
        'view group_term:localgov_event_locality entity',
        'view group_term:localgov_event_price entity',
        'view unpublished group_node:localgov_event entity',
        'delete any group_node:localgov_event content',
        'delete any group_node:localgov_event entity',
        'delete own group_node:localgov_event content',
        'delete own group_node:localgov_event entity',
      ],
      RolesHelper::GROUP_OUTSIDER_ROLE => [
        'view group_node:localgov_event entity',
      ],
    ],
  ];
}
