<?php

/**
 * @file
 * LocalgGov Microsites Group Term UI install file.
 */

/**
 * Implements hook_install().
 */
function localgov_microsites_group_term_ui_install($is_syncing) {

  // Disable the Term view that comes with the group_term module.
  if (!$is_syncing) {
    $view_id = 'group_terms';
    \Drupal::entityTypeManager()->getStorage('view')
      ->load($view_id)
      ->setStatus(FALSE)
      ->save();
  }
}
