<?php

/**
 * @file
 * LocalGov Microsites Blogs module file.
 */

use Drupal\localgov_microsites_group\RolesHelper;

/**
 * Implements hook_modules_installed().
 */
function localgov_microsites_blogs_modules_installed($modules) {
  // Don't use global site pathauto settings.
  //
  // There doesn't seem to be a way to alter configuration when being installed,
  // when it's being saved it's hard to tell where it came from (sync, create,
  // or import). So just removing it after installation.
  $config_factory = \Drupal::configFactory();
  if (in_array('localgov_blogs', $modules) || in_array('localgov_microsites_blogs', $modules)) {
    foreach ([
      'pathauto.pattern.localgov_blog_channel',
      'pathauto.pattern.localgov_blog_post',
    ] as $config_name) {
      if ($config = $config_factory->getEditable($config_name)) {
        $config->delete();
      }
    }
  }
}

/**
 * Implements hook_localgov_microsites_roles_default().
 */
function localgov_microsites_blogs_localgov_microsites_roles_default() {
  return [
    'global' => [
      RolesHelper::MICROSITES_CONTROLLER_ROLE => [
        'view directory facets',
      ],
      RolesHelper::MICROSITES_EDITOR_ROLE => [
        'view directory facets',
      ],
    ],
    'group' => [
      RolesHelper::GROUP_ADMIN_ROLE => [
        'access group_term overview',
        'create group_node:localgov_blog_post entity',
        'create group_node:localgov_blog_channel entity',
        'create group_term:localgov_topic entity',
        'create group_term:localgov_blog_author entity',
        'delete any group_node:localgov_blog_post content',
        'delete any group_node:localgov_blog_post entity',
        'delete any group_node:localgov_blog_channel content',
        'delete any group_node:localgov_blog_channel entity',
        'delete any group_term:localgov_topic content',
        'delete any group_term:localgov_topic entity',
        'delete any group_term:localgov_blog_author content',
        'delete any group_term:localgov_blog_author entity',
        'delete own group_node:localgov_blog_post content',
        'delete own group_node:localgov_blog_post entity',
        'delete own group_node:localgov_blog_channel content',
        'delete own group_node:localgov_blog_channel entity',
        'delete own group_term:localgov_topic content',
        'update any group_node:localgov_blog_post content',
        'update any group_node:localgov_blog_post entity',
        'update any group_node:localgov_blog_channel content',
        'update any group_node:localgov_blog_channel entity',
        'update any group_term:localgov_topic content',
        'update any group_term:localgov_topic entity',
        'update own group_node:localgov_blog_post content',
        'update own group_node:localgov_blog_post entity',
        'update own group_node:localgov_blog_channel content',
        'update own group_node:localgov_blog_channel entity',
        'update own group_term:localgov_topic content',
        'view any unpublished group_term:localgov_topic entity',
        'view group_node:localgov_blog_post content',
        'view group_node:localgov_blog_post entity',
        'view group_node:localgov_blog_channel content',
        'view group_node:localgov_blog_channel entity',
        'view group_term:localgov_topic content',
        'view group_term:localgov_topic entity',
        'view unpublished group_node:localgov_blog_post entity',
        'view unpublished group_node:localgov_blog_channel entity',
      ],
      RolesHelper::GROUP_ANONYMOUS_ROLE => [
        'view group_node:localgov_blog_post entity',
        'view group_node:localgov_blog_channel entity',
      ],
      RolesHelper::GROUP_MEMBER_ROLE => [
        'access group_term overview',
        'create group_node:localgov_blog_post entity',
        'create group_node:localgov_blog_channel entity',
        'create group_term:localgov_topic entity',
        'create group_term:localgov_blog_author entity',
        'delete any group_term:localgov_topic entity',
        'delete any group_term:localgov_blog_author entity',
        'update any group_node:localgov_blog_post content',
        'update any group_node:localgov_blog_post entity',
        'update any group_node:localgov_blog_channel content',
        'update any group_node:localgov_blog_channel entity',
        'update any group_term:localgov_topic entity',
        'update any group_term:localgov_blog_author entity',
        'update own group_node:localgov_blog_post content',
        'update own group_node:localgov_blog_post entity',
        'update own group_node:localgov_blog_channel content',
        'update own group_node:localgov_blog_channel entity',
        'view any unpublished group_term:localgov_topic entity',
        'view any unpublished group_term:localgov_blog_author entity',
        'view group_node:localgov_blog_post entity',
        'view group_node:localgov_blog_channel entity',
        'view group_term:localgov_topic entity',
        'view group_term:localgov_blog_author entity',
        'view unpublished group_node:localgov_blog_post entity',
        'view unpublished group_node:localgov_blog_channel entity',
        'delete any group_node:localgov_blog_post content',
        'delete any group_node:localgov_blog_post entity',
        'delete any group_node:localgov_blog_channel content',
        'delete any group_node:localgov_blog_channel entity',
        'delete own group_node:localgov_blog_post content',
        'delete own group_node:localgov_blog_post entity',
        'delete own group_node:localgov_blog_channel content',
        'delete own group_node:localgov_blog_channel entity',
      ],
      RolesHelper::GROUP_OUTSIDER_ROLE => [
        'view group_node:localgov_blog_post entity',
        'view group_node:localgov_blog_channel entity',
      ],
    ],
  ];
}
