<?php

/**
 * @file
 * LocalGov Microsites Directories module file.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\group\Entity\GroupType;

/**
 * Implements hook_entity_insert().
 */
function localgov_microsites_directories_entity_insert(EntityInterface $entity) {

  if ($entity->getEntityTypeId() != 'localgov_directories_facets') {
    return;
  }

  $group = \Drupal::service('group.group_route_context')->getGroupFromRoute();
  if (empty($group)) {
    return;
  }

  $group_type = GroupType::load($group->bundle());
  $plugin_id = 'group_' . $entity->getEntityTypeId();
  if ($group_type->hasContentPlugin($plugin_id)) {
    $group->addContent($entity, $plugin_id);
  }
}

/**
 * Implements hook_form_alter().
 */
function localgov_microsites_directories_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  // Add submit handler to new directory facet type form.
  if ($form_id == 'localgov_directories_facets_type_add_form') {
    $form['actions']['submit']['#submit'][] = 'localgov_microsites_directories_submit_new_directory_facet_type';
  }

  // Add submit handler to new directory facet form.
  elseif (
    preg_match('/^localgov_directories_facets_[a-zA-Z0-9_]*_add_form$/', $form_id) === 1 &&
    isset($form['#entity_type']) &&
    $form['#entity_type'] == 'localgov_directories_facets'
  ) {
    $form['actions']['submit']['#submit'][] = 'localgov_microsites_directories_submit_new_directory_facet';
  }
}

/**
 * Submit handler for the localgov_directories_facets_type_add_form.
 */
function localgov_microsites_directories_submit_new_directory_facet_type($form, FormStateInterface $form_state) {

  // Redirect back to the directory facet type listing page.
  $group = \Drupal::routeMatch()->getParameter('group');
  if (!is_null($group)) {
    $form_state->setRedirect('entity.group_content.group_localgov_directories_facet_type.list', [
      'group' => $group->id(),
    ]);
  }
}

/**
 * Submit handler for the localgov_directories_facets_TYPE_add_form.
 */
function localgov_microsites_directories_submit_new_directory_facet($form, FormStateInterface $form_state) {

  // Redirect back to the directory facets listing page.
  $group = \Drupal::routeMatch()->getParameter('group');
  $localgov_directories_facets_type = \Drupal::routeMatch()->getParameter('localgov_directories_facets_type');
  if (!is_null($group) && !is_null($localgov_directories_facets_type)) {
    $form_state->setRedirect('view.lgms_group_directory_facets.page', [
      'group' => $group->id(),
      'localgov_directories_facets_type' => $localgov_directories_facets_type,
    ]);
  }
}
