<?php

/**
 * @file
 * LocalGov Microsites Directories module file.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\group\Entity\GroupType;
use Drupal\localgov_microsites_group\RolesHelper;

/**
 * Implements hook_modules_installed().
 */
function localgov_microsites_directories_modules_installed($modules) {
  // Don't use global site pathauto settings.
  //
  // There doesn't seem to be a way to alter configuration when being installed,
  // when it's being saved it's hard to tell where it came from (sync, create,
  // or import). So just removing it after installation.
  $config_factory = \Drupal::configFactory();
  if (in_array('localgov_directories', $modules) ||
    in_array('localgov_directories_page', $modules) ||
    in_array('localgov_directories_venue', $modules) ||
    in_array('localgov_microsites_directories', $modules)
  ) {
    foreach ([
      'pathauto.pattern.localgov_directories_page',
      'pathauto.pattern.localgov_directories_venue',
    ] as $config_name) {
      if ($config = $config_factory->getEditable($config_name)) {
        $config->delete();
      }
    }
  }
  // Directory channel pattern is imported every time optional configuration is
  // refereshed if the item is deleted, so we are just removing it on all module
  // installs.
  if ($config = $config_factory->getEditable('pathauto.pattern.localgov_directory_channel')) {
    $config->delete();
  }
}

/**
 * Implements hook_entity_insert().
 */
function localgov_microsites_directories_entity_insert(EntityInterface $entity) {

  if ($entity->getEntityTypeId() != 'localgov_directories_facets') {
    return;
  }

  $group = \Drupal::service('group.group_route_context')->getGroupFromRoute();
  if (empty($group)) {
    return;
  }

  $group_type = GroupType::load($group->bundle());
  $plugin_id = 'group_' . $entity->getEntityTypeId();
  if ($group_type->hasContentPlugin($plugin_id)) {
    $group->addContent($entity, $plugin_id);
  }
}

/**
 * Implements hook_form_alter().
 */
function localgov_microsites_directories_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  // Add submit handler to new directory facet type form.
  if ($form_id == 'localgov_directories_facets_type_add_form') {
    $form['actions']['submit']['#submit'][] = 'localgov_microsites_directories_submit_new_directory_facet_type';
  }

  // Add submit handler to new directory facet form.
  elseif (
    preg_match('/^localgov_directories_facets_[a-zA-Z0-9_]*_add_form$/', $form_id) === 1 &&
    isset($form['#entity_type']) &&
    $form['#entity_type'] == 'localgov_directories_facets'
  ) {
    $form['actions']['submit']['#submit'][] = 'localgov_microsites_directories_submit_new_directory_facet';
  }
}

/**
 * Submit handler for the localgov_directories_facets_type_add_form.
 */
function localgov_microsites_directories_submit_new_directory_facet_type($form, FormStateInterface $form_state) {

  // Redirect back to the directory facet type listing page.
  $group = \Drupal::routeMatch()->getParameter('group');
  if (!is_null($group)) {
    $form_state->setRedirect('entity.group_content.group_localgov_directories_facet_type.list', [
      'group' => $group->id(),
    ]);
  }
}

/**
 * Submit handler for the localgov_directories_facets_TYPE_add_form.
 */
function localgov_microsites_directories_submit_new_directory_facet($form, FormStateInterface $form_state) {

  // Redirect back to the directory facets listing page.
  $group = \Drupal::routeMatch()->getParameter('group');
  $localgov_directories_facets_type = \Drupal::routeMatch()->getParameter('localgov_directories_facets_type');
  if (!is_null($group) && !is_null($localgov_directories_facets_type)) {
    $form_state->setRedirect('view.lgms_group_directory_facets.page', [
      'group' => $group->id(),
      'localgov_directories_facets_type' => $localgov_directories_facets_type,
    ]);
  }
}

/**
 * Implements hook_localgov_microsites_roles_default().
 */
function localgov_microsites_directories_localgov_microsites_roles_default() {
  return [
    'global' => [
      RolesHelper::MICROSITES_CONTROLLER_ROLE => [
        'access localgov_geo_library entity browser pages',
        'create directory facets',
        'create geo',
        'delete directory facets',
        'delete geo',
        'edit directory facets',
        'edit geo',
        'view directory facets',
      ],
      RolesHelper::MICROSITES_EDITOR_ROLE => [
        'access localgov_geo_library entity browser pages',
        'create directory facets',
        'create geo',
        'delete directory facets',
        'delete geo',
        'edit directory facets',
        'edit geo',
        'view directory facets',
      ],
    ],
    'group' => [
      RolesHelper::GROUP_ADMIN_ROLE => [
        'create group_node:localgov_directories_page entity',
        'create group_node:localgov_directory_promo_page entity',
        'create group_node:localgov_directories_venue entity',
        'create group_node:localgov_directory entity',
        'delete any group_node:localgov_directories_page content',
        'delete any group_node:localgov_directories_page entity',
        'delete any group_node:localgov_directory_promo_page content',
        'delete any group_node:localgov_directory_promo_page entity',
        'delete any group_node:localgov_directories_venue content',
        'delete any group_node:localgov_directories_venue entity',
        'delete any group_node:localgov_directory content',
        'delete any group_node:localgov_directory entity',
        'delete own group_node:localgov_directories_page content',
        'delete own group_node:localgov_directories_page entity',
        'delete own group_node:localgov_directory_promo_page content',
        'delete own group_node:localgov_directory_promo_page entity',
        'delete own group_node:localgov_directories_venue content',
        'delete own group_node:localgov_directories_venue entity',
        'delete own group_node:localgov_directory content',
        'delete own group_node:localgov_directory entity',
        'manage directory facets',
        'update any group_node:localgov_directories_page content',
        'update any group_node:localgov_directories_page entity',
        'update any group_node:localgov_directory_promo_page content',
        'update any group_node:localgov_directory_promo_page entity',
        'update any group_node:localgov_directories_venue content',
        'update any group_node:localgov_directories_venue entity',
        'update any group_node:localgov_directory content',
        'update any group_node:localgov_directory entity',
        'update own group_node:localgov_directories_page content',
        'update own group_node:localgov_directories_page entity',
        'update own group_node:localgov_directory_promo_page content',
        'update own group_node:localgov_directory_promo_page entity',
        'update own group_node:localgov_directories_venue content',
        'update own group_node:localgov_directories_venue entity',
        'update own group_node:localgov_directory content',
        'update own group_node:localgov_directory entity',
        'view group_node:localgov_directories_page content',
        'view group_node:localgov_directories_page entity',
        'view group_node:localgov_directory_promo_page content',
        'view group_node:localgov_directory_promo_page entity',
        'view group_node:localgov_directories_venue content',
        'view group_node:localgov_directories_venue entity',
        'view group_node:localgov_directory content',
        'view group_node:localgov_directory entity',
        'view unpublished group_node:localgov_directories_page entity',
        'view unpublished group_node:localgov_directory_promo_page entity',
        'view unpublished group_node:localgov_directories_venue entity',
        'view unpublished group_node:localgov_directory entity',
      ],
      RolesHelper::GROUP_ANONYMOUS_ROLE => [
        'view group_node:localgov_directories_page entity',
        'view group_node:localgov_directory_promo_page entity',
        'view group_node:localgov_directories_venue entity',
        'view group_node:localgov_directory entity',
      ],
      RolesHelper::GROUP_MEMBER_ROLE => [
        'create group_node:localgov_directories_page entity',
        'create group_node:localgov_directory_promo_page entity',
        'create group_node:localgov_directories_venue entity',
        'create group_node:localgov_directory entity',
        'manage directory facets',
        'update any group_node:localgov_directories_page content',
        'update any group_node:localgov_directories_page entity',
        'update any group_node:localgov_directory_promo_page content',
        'update any group_node:localgov_directory_promo_page entity',
        'update any group_node:localgov_directories_venue content',
        'update any group_node:localgov_directories_venue entity',
        'update any group_node:localgov_directory content',
        'update any group_node:localgov_directory entity',
        'update own group_node:localgov_directories_page content',
        'update own group_node:localgov_directories_page entity',
        'update own group_node:localgov_directory_promo_page content',
        'update own group_node:localgov_directories_promo_age entity',
        'update own group_node:localgov_directories_venue content',
        'update own group_node:localgov_directories_venue entity',
        'update own group_node:localgov_directory content',
        'update own group_node:localgov_directory entity',
        'view group_node:localgov_directories_page entity',
        'view group_node:localgov_directory_promo_page entity',
        'view group_node:localgov_directories_venue entity',
        'view group_node:localgov_directory entity',
        'view unpublished group_node:localgov_directories_page entity',
        'view unpublished group_node:localgov_directory_promo_page entity',
        'view unpublished group_node:localgov_directories_venue entity',
        'view unpublished group_node:localgov_directory entity',
      ],
      RolesHelper::GROUP_OUTSIDER_ROLE => [
        'view group_node:localgov_directories_page entity',
        'view group_node:localgov_directory_promo_page entity',
        'view group_node:localgov_directories_venue entity',
        'view group_node:localgov_directory entity',
      ],
    ],
  ];
}
