name: Test LocalGov Microsites localgovdrupal/localgov_microsites_group drupal-module

on:
  push:
    branches:
      - '4.x'
  pull_request:
    branches:
      - '4.x'
  workflow_dispatch:

jobs:
  tests:
    uses: localgovdrupal/localgov_shared_workflows/.github/workflows/test-microsites.yml@1.x
    with:
      project: 'localgovdrupal/localgov_microsites_group'
      project_path: 'web/modules/contrib/localgov_microsites_group'
